api_platform:
    title: 'Todo List API'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    collection:
        pagination:
            enabled: false
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
